/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Arrays;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test void rollTest() {
        //Arrange
        Library sut = new Library();
        int[] testArray = new int[5];
        //Act
        testArray = sut.roll(5);
        //Assert
assertTrue(testArray.length == 5);
assertTrue(testArray[0] >= 1 && testArray[0] <= 6);
    }

    @Test void duplicateTest() {
        Library sut = new Library();
        int [] array = {2,4,6,2};
        assertTrue(sut.containsDuplicates(array),"Array of {2, 4, 6, 2} asserts true, it contains a duplicate!");
    }

    @Test void testCaculateArrayAverage(){
        //ARRANGE
Library sut = new Library();
int[] testArray = {66, 64, 58, 65, 71, 57, 60};
        //ACT
int result = sut.calculateAverage(testArray);
        //ASSERT
        assertNotNull(result);
        assertEquals(0, (result * 0));
    }

    @Test void testLowestAverageArray(){
        //ARRANGE
        Library sut = new Library();
        int[][] testArray = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {1, 1, 1, 1, 1, 1, 1}
        };
        //ACT
int[] result = sut.lowestAverageArray(testArray);
int[] expectedArray =  (testArray[3]);
        //ASSERT
        assertNotNull(result);
        assertEquals(expectedArray, (result));
    }
}
