/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.*;

public class Library {
    public int[] roll(int n) {
        Random rand = new Random();
        int[] diceNum = new int[n];
        for(int i = 0; i < n; i++) {
            int randNum = rand.nextInt(6);
            diceNum[i] = randNum + 1;
        }
        return diceNum;
    }

public boolean containsDuplicates(int[] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = 1; j < array.length; j++) {
                if (i == j) continue;
                if (array[i] == array[j])
                    return true;
            }
        }
        return false;
}
//Caculating Averages
    public static int calculateAverage(int[] arrayOfValues) {
int sum = 0;
int arrayLength = arrayOfValues.length;
//FOR LOOP
        for (int i = 0; i < arrayOfValues.length; i++) {
            //every iteration we add value to sum
            sum = sum + arrayOfValues[i];
        }
        //sum of all values / length of array
        return (sum/arrayLength);
    }

    public class App {
        static int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
    }

    public static int[] lowestAverageArray(int[][] weeklyMonthTemperatures) {
        int[] lowestAverageArray = weeklyMonthTemperatures[0];
        int lowestAverage = calculateAverage(weeklyMonthTemperatures[0]);
        for (int i = 0; i < weeklyMonthTemperatures.length; i++) {
            int currentArrayAverage = calculateAverage(weeklyMonthTemperatures[i]);
            if(currentArrayAverage < lowestAverage){
                lowestAverageArray = weeklyMonthTemperatures[i];
            }
        }
        return lowestAverageArray;
    }

    public int findAverageOfArray(int[] array){
        return 0;
    }

}
