/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

// got code from
// https://github.com/snur206/java-fundamentals/tree/main/inheritance